name: A
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    # Step 1: Download Remote.it CLI
    - name: Download Remote.it CLI
      run: |
        Invoke-WebRequest https://downloads.remote.it/desktop/v3.34.4/Remote.It-Installer-x64.exe -OutFile remoteit.exe
        Invoke-WebRequest https://raw.githubusercontent.com/AnshumanPM/ngrok-rdp/main/resources/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/AnshumanPM/ngrok-rdp/main/resources/winrar.exe -OutFile winrar.exe

    # Step 2: Install Remote.it and Configure Account
    - name: Install Remote.it CLI
      run: |
        .\remoteit.exe login -u $Env:REMOTEIT_USERNAME -p $Env:REMOTEIT_PASSWORD
      env:
        REMOTEIT_USERNAME: ${{ secrets.REMOTEIT_USERNAME }}
        REMOTEIT_PASSWORD: ${{ secrets.REMOTEIT_PASSWORD }}

    # Step 3: Register the Device
    - name: Register Device with Remote.it
      run: |
        .\remoteit.exe device register --name "WindowsRDP" --type "pc"

    # Step 4: Enable RDP Access
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy winrar.exe C:\Users\Public\Desktop\winrar.exe

    # Step 5: Add RDP Service to Remote.it
    - name: Add RDP Service to Remote.it
      run: |
        .\remoteit.exe service add --device-name "WindowsRDP" --name "RDP" --port 3389 --protocol tcp
        
